### PR TITLE
Firestore filtering for old processed queue

### PR DESCRIPTION
**Pull request by hughgrigg**

### CODE REVIEW

**Comment by simon--poole** [comment]
So the exact database call I'm having issues with was this:

`const queueDocs = await this.db
            .collection(this.getQueueDocumentPath(name, null))
            .where('processed' as any, '==' as any, true as any)
            .where('attributes.processed', '<' as any, filterTimestamp.toISOString())
            .limit(trimmingConfig.queueBatchSize)
            .get()`
`InProcessFirestoreQuerySnapshot {
      docs: [],
      ...
}`
It was returning 0 documents - commenting out the second where correctly returns the amount of documents expected.

**Comment by hughgrigg** [comment]
> So the exact database call I'm having issues with was this:
> 
> `const queueDocs = await this.db .collection(this.getQueueDocumentPath(name, null)) .where('processed' as any, '==' as any, true as any) .where('attributes.processed', '<' as any, filterTimestamp.toISOString()) .limit(trimmingConfig.queueBatchSize) .get()`
> `InProcessFirestoreQuerySnapshot { docs: [], ... }`
> It was returning 0 documents - commenting out the second where correctly returns the amount of documents expected.

Thanks, I'll see if I can reproduce the empty result with that query.

**Comment by hughgrigg** [comment]
@simon--poole See the updated test -- it still passes 🤔 Can you double-check the data structure and query looks the same? I'll see if I can debug it in the other repo in the meantime.

**Comment by simon--poole** [comment]
I don't see any issues with the data structure in the test, weirdly.
This is a sample test queue item I'm using
```
{ id: '839aace1302f0d8907f58ddf84d64f0b891d',
      name: '__inttests',
      body: { value: 6379, commandName: 'TestCommand' },
      processed: true,
      failed: false,
      attributes: 
       { written: ServerTimestampTransform {},
         created: '2019-01-01T00:00:00.000Z',
         processed: '2019-01-01T00:00:00.000Z',
         failureMessage: null } }
```

**Pull request merged**
